services:
    bot:
        build: ./app
        restart: unless-stopped                                                                                                             
        volumes:
            - ./conf:/app/conf
        environment:
            - TELEGRAM_API_TOKEN=$TELEGRAM_API_TOKEN
            - TZ=$TZ
            - SECRET_COMMAND=$SECRET_COMMAND